version: '3'

volumes:
  data:

services: 
  database:
    image: 'postgres:13'
    ports: 
    - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password=123
      POSTGRES_DB: default_database
      